### ISSUE TITLE
EPIC - Extract skills ‘communities’ from job ads

### ISSUE THREAD

**Issue by lizgzil** [nestauk/skills-taxonomy-v2#6]
## Goal

Find skill communities using the [Industrial Taxonomy](https://github.com/nestauk/industrial-taxonomy) pipeline.

- Tokenise and lemmatise job descriptions
- Use TFIDF & VADER to remove generic terms
- Create a co-occurrence network of words 
- Use community modelling to identify communities 
- Identify salient terms in the communities and use these to tag job ads with skills - Compare average word2vec job ads to do this

## Output

List of extracted skills per job ad.

## Issues
This is an epic issue. List of individual issues is below:

- [x] Explore potential for ML to remove unnecessary text from job advert #4 #30 
- [ ] Refactor sentence classifer for use #19 
- [ ] Try out Industrial Taxonomy algo on sample #17 
- [ ] Try out embeddings + clustering approach to get skills #22 
- [ ] Think about how to name skills #33
